# Site settings
title: XyzMax
email: 763305825@qq.com
description: Max的博客 开源爱好者
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  maxtan
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown

paginate: 10
paginate_path: "page:num"
timezone: Asia/Shang_Hai
# highlight
# 本地用rouge, github上用pygments
# highlighter: pygments
# highlighter: rouge
# highlighter: false
